### PR TITLE
Revised Ubuntu guide with more context.

### PR DESCRIPTION
**Pull request by dwatley**
I've updated the Ubuntu guide with more context and more thorough instructions. This includes:

-  Updating the guide to use more recent software versions.
-  Removing outdated content around MongoDB 2.6.x.
-  Removing details around non-existent NodeBB branches.
-  Adding additional instruction around MongoDB administration, configuration as well as details around missing permissions for cluster monitoring.
-  Adding a systemd component for managing NodeBB.

I ran through entire setup using my changes and was successful.

### CODE REVIEW

**Comment by dwatley** [comment]
Woot. Hoping it helps. :)

**Comment by pichalite** [comment]
@julianlam This needs to be reverted. `sudo` for everything?

**Comment by julianlam** [comment]
Hm, that is correct, the NodeBB related commands do not require sudo, good eye @pichalite

**Comment by pichalite** [comment]
Well it was noticed in this thread. https://community.nodebb.org/topic/10712/nodebb-does-not-work-i-can-not-reset

**Comment by dwatley** [comment]
Well an option would have been to su instead, sure. It's been a while since I've tinkered around with this, but because of the default permissions of the location (/opt) and the desire to set it up with systemd as a system service I went the route I did. It seems that user forgot to adjust the permissions of the nodebb directory based on https://community.nodebb.org/post/60416

I was very particular about running through the guide end-to-end before submitting this PR.

**Comment by pitaj** [comment]
No, what we're saying is that installing NodeBB with sudo is wrong. If you need to create the directory with sudo in the first place, sure, do that, but then `chown` it to a different user and then run git, npm, etc as that user instead.

**Comment by dwatley** [comment]
Doh, thanks.

**Comment by julianlam** [comment]
On a second read-through, @dwatley's approach is still secure. He `chown`s the entire `/opt/nodebb` directory in the end. Therefore there's no need to revert the PR at all, it is okay.

**Comment by julianlam** [comment]
That said, I've re-written it to install it to the user's home folder and removed the `nodebb` user creation step.

**Pull request merged**
