### PR TITLE
Ubuntu doesnt have Python by default, so npm install breaks

### PR DESCRIPTION
**Pull request by gorkem-cetin**

### CODE REVIEW

**Comment by julianlam** [comment]
What error do you get when you try installing? Under Ubuntu 14.04, python doesn't seem to require separate installation...

**Comment by gorkem-cetin** [comment]
This is what I get: 

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:116:14)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:49:11
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:78:16)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:82:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:93:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)

I tried with Ubuntu 15.04 btw, 14.04 is ~1.5 years old.

**Comment by julianlam** [comment]
> I tried with Ubuntu 15.04 btw, 14.04 is ~1.5 years old.

That may be so, but we try to track the LTS versions as they are the most stable :smile:

**Comment by gorkem-cetin** [comment]
True - Just wanted to point out that I've first created a DO image (even didnt choose the latest version), and then followed the installation instructions "thinking aloud" that whatever works for 14.04 would be working for 15.04. Btw, I have encountered another issue "Internal error. Oops! Looks like something went wrong!" but probably again thats because I use a newer version. 

Anyhow, thanks :)

**Comment by julianlam** [comment]
The odd part is we have it running on 15.04 as well, so I'm not quite sure why python wasn't installed. To my knowledge, it is always installed as part of a base installation...

**Pull request closed without merging**
