### PR TITLE
Rewritten and use 0.7.x branch on installs

### PR DESCRIPTION
**Pull request by Firelad97**
Needs confirmation though. It works perfectly for me. ;)

### CODE REVIEW

**Comment by unixfox** [comment]
I'll try it now.

**Comment by unixfox** [comment]
Why use a cartridge ? Openshift support NodeJS.

**Comment by Firelad97** [comment]
Yes Openshift supports NodeJS, but it's outdated. Had to use a up-to-date so v0.7.x will work on Openshift.

**Comment by Firelad97** [comment]
Hey, I'm still waiting. Does it works?

**Comment by unixfox** [comment]
I didn't have time to try it. I'll try if I've some free time.

**Comment by unixfox** [comment]
According to [this comment](https://github.com/NodeBB/nodebb-english/pull/43#issuecomment-108780947) I'll merge your work.

**Pull request merged**
