### PR TITLE
Added section on how to configure Nginx to use a custom error page

### PR DESCRIPTION
**Pull request by henrywright**
I'm not sure I've put this guide in the right place so feel free to move it to another page if necessary.

### CODE REVIEW

**Comment by psychobunny** [comment]
Looks good! Except the Notes: section at the bottom. The way it's structured it feels like the "notes" section belongs to the 502 instructions section and not in general, if you see what I mean.

https://github.com/henrywright/nodebb-english/blob/master/configuring/proxies/nginx.rst

**Comment by henrywright** [comment]
I see what you mean! Amendment incoming...

**Comment by psychobunny** [comment]
Awesome. Looks good thanks! :+1:

**Comment by henrywright** [comment]
Now back to Easter egg hunting... hehe

**Pull request merged**
