### PR TITLE
Adding Custom Hooks to plugins documentation

### PR DESCRIPTION
**Pull request by LewisMcMahon**

### CODE REVIEW

**Comment by LewisMcMahon** [comment]
Have you guys not got the webhook setup for RTD? if you have its not working

**Comment by psychobunny** [comment]
I do have the webhooks setup, can you try hard refresh / clear cache?

**Comment by julianlam** [comment]
I don't think it's been working for awhile now... at least I've been manually building it when I make changes...

**Comment by LewisMcMahon** [comment]
The stuff i added should appear above testing https://nodebb-francais.readthedocs.org/projects/nodebb/en/latest/plugins/create.html

**Comment by julianlam** [comment]
Not sure about `francais`, but it should be here, actually https://docs.nodebb.org/en/latest/plugins/create.html

:smile:

**Comment by julianlam** [comment]
Looks like the last build was 21 hours ago, so I guess the webhook isn't working anymore.

**Comment by LewisMcMahon** [comment]
@julianlam not sure how i ended up on the french, English is the one i added it to.

**Pull request merged**
