### PR TITLE
unifying socket and http requests in CLS

### PR DESCRIPTION
**Pull request by akhoury**

### CODE REVIEW

**Comment by akhoury** [comment]
relates to https://github.com/NodeBB/NodeBB/pull/4162

**Comment by akhoury** [comment]
@julianlam please merge, because the old info are wrong and revert
https://github.com/NodeBB/NodeBB/commit/bc0359475c8f897c2133ffe1658599a194da6195

**Comment by julianlam** [comment]
Did the link change now?

**Comment by akhoury** [comment]
yup
https://docs.nodebb.org/en/latest/plugins/create.html#getting-a-reference-to-each-request-from-within-any-plugin-hook

**Comment by julianlam** [comment]
:+1:

**Pull request merged**
