### PR TITLE
make /uploads/files work

### PR DESCRIPTION
**Pull request by vstoykovbg**
for backward compatibility

### CODE REVIEW

**Comment by pitaj** [comment]
This is a handy tip, but the title seems to be misleading. Nothing should be broken if your nginx config was set up correctly. If it is broken, then you should report that as a bug.

**Comment by vstoykovbg** [comment]
I did not tested it, however it is obvious that requests for /uploads/* will be passed to NodeBB instead served directly by Nginx.

My suggestions prevents this: requests will be served directly by Nginx without invoking NodeBB.

**Comment by pitaj** [comment]
While it is true that the initial request is handle by NodeBB, NodeBB merely redirects the browser to `/assets/uploads` instead. The files are then served by nginx.

**Comment by julianlam** [comment]
As we're no longer moving uploads to assets folder, this should be moot now.

**Pull request closed without merging**
